#%RAML 1.0
title: 证书类型，证书，证书需求
version: v1
baseUri: /{version}
protocols: [HTTP]
mediaType: application/json
      
types:
  category:
    displayName: 证书类型
    type: object
    properties:
      id:
        description: 类型标识
        required: true
        example: "10"
      name:
        description: 类型名称
        required: true
        example: "井控证"
      organ:
        description: 发证机关
        required: true
        example: "培训中心"
      valid:
        description: 有效期
        required: true
        example: "36"
      remark:
        description: 备注
        required: true
        example: "备注"
  cert:
    displayName: 证书
    type: object
    properties:
      id:
        description: 证书编号
        required: true
        example: "10"
      user:
        description: 持证人
        required: true
        type: object
        example: 
          id: "1"
          name: "san.zhang"
      obtainDate:
        description: 获证日期
        required: true
        example: "20180410"
      expiredDate:
        description: 过期日期
        required: true
        example: "20190410"
      category:
        description: 证书类型
        required: true
        type: object
        example: 
            id:"1"
            name:"井控证"
      scanning:
        description: 证书扫描件
        required: true
        example: "http://example.com/scanning.jpg"
      remark:
        description: 备注
        required: true
        example: "备注"
    requirement:
      displayName: 岗位证书需求
      type: object
      properties:
        id:
          description: 需求编号
          required: true
          example: "10"
        position:
          description: 岗位
          required: true
          type: object
          example: 
            id: "1"
            name: "砖井工"
        categorys:
          description: 需求证书类型
          required: true
          example: [
            {"id":"1","name":"井控证"},
            {"id":"2","name":"健康证"},
          ]
traits:
  conflict_exception:
    responses:
      500:
        body:
          application/json:
            type: object
            properties:
              message: string
            example:
              message: <<message>>

  not_found:
    responses:
      404:
        body:
          application/json:
            type: object
            properties:
              message:
                type: string
            example:
              message: not_found


  success:
    responses:
      200:
        body:
          application/json:
            type: object
            properties:
              message:
                type: string
            example:
              message: action_succeed

  fail:
    responses:
      500:
        body:
          application/json:
            type: object
            properties:
              message: string
              reason: string
            example:
              message: action_failed
              reason: <<reason>>

  category_example:
    responses:
      200:
        body:
          application/json:
            example:
              id: "2"
              name: "井控证"
              organ: "培训中心"
              valiad: "36"

  cert_example:
    responses:
      200:
        body:
          application/json:
            example:
              id: "2"
              owner: {"id":"2","name":"李四"}
              obtainDate: "20180101"
              expiredDate: "20190101"
              category: {"id":"2","name":"硫化氢证"}
              scanning: "http://example.com/scanning.jpg"
              remark: "备注"
  
  requirement_example:
    responses:
      200:
        body:
          application/json:
            example:
              id: "1"
              position: {"id":"1","name":"转井工"}
              categorys: [{"id":"1","name":"井控证"},{"id":"2","name":"硫化氢证"}]
              
resourceTypes:
  collection:
    usage: 用于常规的增删查改
    description: <<resourcePathName>> 的集合管理
    get?:
      description: 获取全部 <<resourcePathName>>
      responses:
        200:
          body:
            application/json:
              type: <<resourcePathName>>
    post?:
      description: 创建一个新的 <<resourcePathName | !singularize>>
      responses:
        200:
          body:
            application/json:
              type: <<resourcePathName | !singularize>>

  single:
    description: 指定 <<resourcePathName | !singularize>> 的操作
    is: [not_found]

    get?:
      description: 获取指定 <<resourcePathName>> 的操作
      responses:
        200:
          body:
            application/json:
              type: <<resourcePathName | !singularize>>

    put?:
      description: 修改指定 <<resourcePathName>> 的操作
      is: [conflict_exception: {message: update_failed}]
      responses:
        200:
          body:
            application/json:
              type: <<resourcePathName | !singularize>>

    delete?:
      description: 删除指定 <<resourcePathName>> 的操作
      is: [success,  conflict_exception: {message: delete_disallow}]

/category:
  get:
    description: 查看证书类型列表
    queryParameters:
      name:
        description: "类型名称"
        required: false
        pattern: "井控证" 
      organ:
        description: "发证机关"
        required: false
        pattern: "培训中心"
      page_index:
        description: "查询页数"
        required: false
        pattern: "1"
      page_size:
        description: "每页记录条数"
        required: false
        pattern: "20"
    responses:
      200:
        body:
          application/json:
            example: |
              [
                {
                  "id": "2",
                  "name": "井控证",
                  "organ": "培训中心",
                  "valiad": "36",
                },
                {
                  "id": "3",
                  "name": "硫化氢证书",
                  "organ": "培训中心",
                  "valiad": "36",
                },
              ]
  post:
    description: "新增证书类型"
    queryParameters:
      name:
        description: 类型名称
        required: true
        example: "井控证"
      organ_id:
        description: 发证机构
        required: true
        example: "1"
      valiad:
        description: 有效期
        required: true
        example: "12"
      remark:
        description: 备注
        required: false
        example: ""
    responses: 
      200:
        body: 
          application/json:
            example: 
              status: 200
              message: "SUCCESS"

  /{id}:
    type: single
    uriParameters:
      id:
        description: 证书类型编号
        example: "2"
    get:
      is: [category_example]
  
    put:
      description: "修改指定证书类型"
      queryParameters:
        id:
          description: 证书类型编号
          example: "10"
        name:
          description: 新的证书类型名称
          required: false
          type: string
          example: "井控证书"
        organ_id:
          description: 新的发证机构编号
          required: false
          example: "2"
        valiad:
          description: 新的有效期
          example: "12"

      responses: 
       200:
        body: 
          application/json:
            example:
              status: 200
              message: "SUCCESS"
    delete:
        description: "删除指定证书类型"
        queryParameters:
        id:
            description: "证书类型编号"
            example: "1"
        responses: 
         200:
           body: 
            application/json:
                example: 
                  status: 200
                  message: "SUCCESS"

/cert:
  get:
    description: 查看证书列表
    queryParameters:
      category_name:
        description: "类型名称"
        required: false
        pattern: "井控证" 
      owner_name:
        description: "持证人"
        required: false
        pattern: "张三" 
      invalid_date:
        description: "到期天数"
        required: false
        pattern: "50" 
      own_start:
        description: "获证开始时间"
        required: false
        pattern: "20180101" 
      own_start:
        description: "获证结束时间"
        required: false
        pattern: "20180410"
      page_index:
        description: "查询页数"
        required: false
        pattern: "1"
      page_size:
        description: "每页记录条数"
        required: false
        pattern: "20"
    responses:
      200:
        body:
          application/json:
            example: |
              [
                {
                  "id":"1",
                  "owner":{"id":"1","name":"张三"},  
                  "obtainDate":"20180101",
                  "expiredDate":"20190101",
                  "category": {"id":"1","name":"井控证","organ":{"id":"1","name":"培训中心"}},  
                  "scanning":"http://example.com/scanning.jpg",
                  "remark":"备注"
                },
                {
                  "id":"2",
                  "owner":{"id":"2","name":"李四"},  
                  "obtainDate":"20180101",
                  "expiredDate":"20190101",
                  "category": {"id":"1","name":"硫化氢证","organ":{"id":"1","name":"培训中心"}},  
                  "scanning":"http://example.com/scanning.jpg",
                  "remark":"备注"
                }
              ]
  post:
    description: "新增证书"
    queryParameters:
      category_id:
        description: 类型编号
        required: true
        example: "1"
      owner_id:
        description: 人员编号
        required: true
        example: "1"
      obtainDate:
        description: 获证日期
        required: true
        example: "20180101"
      scanning:
        description: 扫描件地址
        required: true
        example: "1"
      remark:
        description: 备注
        required: false
        example: ""
      
    responses: 
      200:
        body: 
          application/json:
            example: 
              status: 200
              message: "SUCCESS"

  /{id}:
    type: single
    uriParameters:
      id:
        description: 证书编号
        example: "2"
    get:
      is: [cert_example]

    put:
      description: "修改指定证书信息"
      queryParameters:
        id:
          description: 证书编号
          example: "10"
        category_id:
          description: 证书类型编号
          required: false
          example: "10"
        owner_id:
          description: 新的持证人
          required: false
          type: string
          example: "张三"
        obtainDate:
          description: 新的获证日期
          required: false
          example: "2"
        scanning:
          description: 新的扫描件
          required: false
          example: "http://example.com/scanning2.jpg"
        remark:
          description: 新的备注
          example: "备注"

      responses: 
       200:
        body: 
          application/json:
            example: 
              status: 200
              message: "SUCCESS"
    delete:
        description: "删除指定证书"
        queryParameters:
        id:
            description: "证书编号"
            example: "1"
        responses: 
         200:
          body: 
            application/json:
                example: 
                  status: 200
                  message: "SUCCESS"


/requirement:
  get:
    description: 查看岗位证书需求列表
    queryParameters:
      position_id:
        description: "岗位编号"
        required: false
        pattern: "1" 
      page_index:
        description: "查询页数"
        required: false
        pattern: "1"
      page_size:
        description: "每页记录条数"
        required: false
        pattern: "20"
    responses:
      200:
        body:
          application/json:
            example: |
              [
                {
                  "id":"1"
                  "position":{"id":"1","name":"转井工"}
                  "categorys":[{"id":"1","name":"井控证"},{"id":"2","name":"硫化氢证"}]
                },
                {
                  "id":"2"
                  "position":{"id":"2","name":"化学工"}
                  "categorys":[{"id":"1","name":"井控证"},{"id":"2","name":"硫化氢证"}]
                }
              ]

  post:
    description: "岗位证书需求"
    queryParameters:
      position_id:
        description: 岗位编号
        required: true
        example: "1"
      category_ids:
        description: 需求证书类型列表
        required: true
        example: ["1","3","5"]

    responses: 
      200:
        body: 
          application/json:
            example: 
              status: 200
              message: "SUCCESS"

  /{id}:
    type: single
    uriParameters:
      id:
        description: 需求编号
        example: "2"
    get:
      is: [requirement_example]

    put:
      description: "修改岗位需求"
      queryParameters:
        id:
          description: 需求编号
          example: "10"
        category_ids:
          description: 新的证书需求类型
          required: false
          type: string
          example: ["1","2","3"]
      responses: 
       200:
        body: 
          application/json:
            example: 
              status: 200
              message: "SUCCESS"
    delete:
        description: "删除岗位需求"
        queryParameters:
        id:
            description: "需求编号"
            example: "1"
        responses: 
         200:
          body: 
            application/json:
                example: 
                  status: 200
                  message: "SUCCESS"


                